
pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "thumatvu87/devops-app:latest"
  }

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/thumatvu87/devops-ci-app.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $DOCKER_IMAGE .'
      }
    }

    stage('Run Unit Tests') {
      steps {
        sh 'docker run --rm $DOCKER_IMAGE python3 test_app.py'
      }
    }

    stage('Push to DockerHub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
          sh 'docker push $DOCKER_IMAGE'
        }
      }
    }

    stage('Deploy to EC2') {
      steps {
        sh 'scp -o StrictHostKeyChecking=no deploy.sh ec2-user@<EC2-IP>:/home/ec2-user/'
        sh 'ssh -o StrictHostKeyChecking=no ec2-user@<EC2-IP> "bash deploy.sh"'
      }
    }
  }
}
